version: '3.7'

x-env: &env
  MYSQL_USER: omp
  MYSQL_PASSWORD: omp
  MYSQL_DB: omp

services:
  omp3:
    build:
      context: .
      args:
        <<: *env
    image: dainst/cilantro-omp3
    volumes:
    - ./omp:/var/www/html
    ports:
      - "4444:80"
